In [1]:
import numpy as np

In [2]:
a = np.array([6,7,8])

In [3]:
a

array([6, 7, 8])

In [4]:
a[0]

6

In [5]:
a[1]

7

In [6]:
a = np.array([[6,7,8],[2,4,6]])

In [7]:
a

array([[6, 7, 8],
       [2, 4, 6]])

In [8]:
a.ndim

2

In [9]:
a.itemsize

4

In [10]:
a.dtype

dtype('int32')

In [12]:
a = np.array([[6,7,8],[2,4,6]], dtype = np.float64)

In [13]:
a

array([[6., 7., 8.],
       [2., 4., 6.]])

In [14]:
a.itemsize

8

In [15]:
a.dtype

dtype('float64')

In [16]:
a.shape

(2, 3)

In [17]:
a = np.array([[6,7,8],[2,4,6]], dtype = np.complex)

In [18]:
a.dtype

dtype('complex128')

In [19]:
a

array([[6.+0.j, 7.+0.j, 8.+0.j],
       [2.+0.j, 4.+0.j, 6.+0.j]])

In [20]:
b = np.zeros((5,7))

In [21]:
b

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [22]:
c = np.ones((2,2))

In [23]:
c

array([[1., 1.],
       [1., 1.]])

In [24]:
np.arange(1,5)

array([1, 2, 3, 4])

In [25]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [26]:
np.linspace(1,7,10)

array([1.        , 1.66666667, 2.33333333, 3.        , 3.66666667,
       4.33333333, 5.        , 5.66666667, 6.33333333, 7.        ])

In [27]:
np.linspace(1,10,10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [28]:
e = np.array([[1,2],[3,4],[5,6]]) 

In [29]:
e

array([[1, 2],
       [3, 4],
       [5, 6]])

In [30]:
e.shape

(3, 2)

In [31]:
e.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [32]:
e.reshape(6,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [34]:
e.ravel()

array([1, 2, 3, 4, 5, 6])

In [35]:
e

array([[1, 2],
       [3, 4],
       [5, 6]])

In [36]:
e.min()

1

In [37]:
e.max()

6

In [38]:
e.sum()

21

In [40]:
e.sum(axis=0)

array([ 9, 12])

In [41]:
e.sum(axis=1)

array([ 3,  7, 11])

In [42]:
np.sqrt(e)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ],
       [2.23606798, 2.44948974]])

In [43]:
np.std(e)

1.707825127659933

In [45]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

In [47]:
x+y

array([[ 6,  8],
       [10, 12]])

In [48]:
x*y

array([[ 5, 12],
       [21, 32]])

In [49]:
x/y

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

In [50]:
x.dot(y)

array([[19, 22],
       [43, 50]])